# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: gustavosiqueira
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: teste-tecnico-sls

service: agendamento-service

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1

functions:
  getAgendas:
    handler: src/handler.getAgendas
    events:
      - http:
          path: agendas
          method: get
  createAgendamento:
    handler: src/handler.createAgendamento
    events:
      - http:
          path: agendamento
          method: post

custom:
  serverless-offline:
    httpPort: 3000
